### ISSUE TITLE
DiscreteFourierTransform

### ISSUE THREAD

**Issue by xin-1998** [Trisia/randomness#1]
您好，我在调用您的随机数自检程序中，我使用15种算法 上电自检报错，12种算法 上电自检没有问题，测试LunearComplexity和MaurerUniversal没有问题。
在调用到用到DiscreteFourierTransform函数使用两个以上random.dat会报错，每个文件为129KB，
使用go版本1.16，win11系统
检测文件夹里面随机数文件方法使用您最初测试方法：
var files []io.Reader
	dirname := "E:\\dean\\testRandom\\random"
	dirs, err := ioutil.ReadDir(dirname)
报错信息如下：
=== RUN   TestDiscreteFourierTransform
--- FAIL: TestDiscreteFourierTransform (0.03s)
panic: fft input length must be < 1048576. It is: 2097152 [recovered]
	panic: fft input length must be < 1048576. It is: 2097152

goroutine 6 [running]:
testing.tRunner.func1.2(0x3777a0, 0xc000040000)

	F:/GO/src/testing/testing.go:1143 +0x345
testing.tRunner.func1(0xc000035080)
	F:/GO/src/testing/testing.go:1146 +0x4b6
panic(0x3777a0, 0xc000040000)
	F:/GO/src/runtime/panic.go:965 +0x1c7
github.com/Trisia/randomness.DiscreteFourierTransformTest(0xc000260000, 0x200000, 0x200000, 0xc000260000)
	F:/GOPATH/pkg/mod/github.com/!trisia/randomness@v1.2.2/discrete_fourier_transform.go:60 +0x4f5
github.com/Trisia/randomness.DiscreteFourierTransformTestBytes(0xc0001e0000, 0x40000, 0x7fe00, 0x40000)
	F:/GOPATH/pkg/mod/github.com/!trisia/randomness@v1.2.2/discrete_fourier_transform.go:28 +0x68
github.com/Trisia/randomness.DiscreteFourierTransform(...)
	F:/GOPATH/pkg/mod/github.com/!trisia/randomness@v1.2.2/discrete_fourier_transform.go:22
testR-ando_test.TestDiscreteFourierTransform(0xc000035080)
	E:/dean/testRandom/detect_test.go:189 +0x1e6

testing.tRunner(0xc000035080, 0x3aa618)
	F:/GO/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	F:/GO/src/testing/testing.go:1238 +0x2b3

进程 已完成，退出代码为 1

**Comment by Trisia** [comment]
能否put一些报错时的代码，以及测试数据集。

**Comment by Trisia** [comment]
请提供报错代码以及报错的数据集。

**Comment by Trisia** [comment]
数据集的长度可能有问题，在 GMT0005-2021 中描述离散傅里叶检测3中数据检测长度 20 000bit、1 000  000bit、100 000 000bit

输入的数据集应该符合相应长度

> 注: 8bit = 1 byte
