### ISSUE TITLE
detect/detect.go 中的 PeriodDetect 方法未对 distributions 变量进行赋值

### ISSUE THREAD

**Issue by dmahacker** [Trisia/randomness#11]
![image](https://github.com/Trisia/randomness/assets/8119999/a32ba290-70e4-45cd-9e47-6c6bb756afe5)

会导致跑PeriodDetect总是失败

**Comment by emmansun** [comment]
你能把你遇到的错误信息分享出来，而不是只是简单的一张图吗？

**Comment by dmahacker** [comment]
我截图的就是这个库的代码呀，如果一定要说报错，那就是库内置的test都无法正常运行
比如分别执行detect/detect_test.go里的TestPowerOnDetect和TestPeriodDetect方法，TestPowerOnDetect能通过，TestPeriodDetect无法通过
![image](https://github.com/Trisia/randomness/assets/8119999/60752516-bb8c-47aa-9e51-8f2ac1f2c364)
![image](https://github.com/Trisia/randomness/assets/8119999/8a05fc19-4e8b-4d2d-999a-102287e95e37)

以上所有截图和代码都是这个库里的代码和对应代码的运行结果，没有我自己的代码，我是来提一个我觉得有问题的地方
不知道这样讲您能否理解

**Comment by emmansun** [comment]
你可以提交一个PR

**Comment by Trisia** [comment]
#c4303bf420328896634a10d51c164543c32a549f

**Comment by Trisia** [comment]
fixed in v1.4.1
