### ISSUE TITLE
判定支持？

### ISSUE THREAD

**Issue by fishfly123** [Trisia/randomness#13]
能否支持一下《GM/T0005 2021 随机性检测规范》 “样本通过率判断”和“样本均匀性判断”

**Comment by Trisia** [comment]
![image](https://github.com/Trisia/randomness/assets/17817790/ce79c5b8-e65c-4c82-aa32-b3898c242c1f)
https://pkg.go.dev/github.com/Trisia/randomness@v1.4.1/detect#Threshold
